services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    restart: always
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

